spring:
  application:
    name: discoveryserver

server:
  port: 8888


eureka:
  client:
    serviceUrl:
      registerWithEureka: false
      fetchRegistry: false
      defaultZone: http://localhost:8888/eureka/
